### ISSUE TITLE
Make shift-enter work more predictably

### ISSUE THREAD

**Issue by computerdane** [danerieber/harmon-react#4]
Currently, shift+enter makes a newline. However, when there are multiple lines in the chat, pressing enter creates newlines, and you have to use control+enter to then send the message. This confused John and he wants to fix it.

Fix it, John.

**Comment by jojxd** [comment]
fixed in https://github.com/danerieber/harmon-react/pull/8

**Comment by jojxd** [comment]
idiot

**Comment by computerdane** [comment]
https://github.com/danerieber/harmon-react/pull/8
